all:
  vars:
    ansible_user: vagrant
    ansible_become: true

  children:

    postgres:
      hosts:
        db1:
          ansible_host: 10.10.10.11
          patroni_name: db1
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/db1

        db2:
          ansible_host: 10.10.10.12
          patroni_name: db2
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/db2

        db3:
          ansible_host: 10.10.10.13
          patroni_name: db3
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/db3

    loadbalancers:
      hosts:
        lb1:
          ansible_host: 10.10.10.21
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/lb1

        lb2:
          ansible_host: 10.10.10.22
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/lb2

    etcd:
      hosts:
        db1:
        db2:
        db3:

    backup:
      hosts:
        backup1:
          ansible_host: 10.10.10.31
          ansible_ssh_private_key_file: ~/.ssh/vagrant-keys/backup1

    monitoring:
      hosts:
        db1:
