---
- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started