---
etcd_user: etcd
etcd_group: etcd

etcd_binary_dir: /usr/local/bin
etcd_config_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd

etcd_version: "3.6.14"

etcd_client_port: 2379
etcd_peer_port: 2380

etcd_initial_cluster_state: new
etcd_initial_cluster_token: postgres-ha-etcd